# To build an image with this Dockerfile:
# docker build -t rdkit-knime-linux -f Dockerfile_linux_x86_64 --network=host $@ .

# To run bash in the built image mounting a local dir inside the container:
# mkdir -p ../knime_dlls && docker run -u root --network=host --mount type=bind,source="$(pwd)/.."/knime_dlls,target=/knime_dlls -it rdkit-knime-linux:latest bash

FROM centos:7 AS GCC_TOOL_CHAIN

USER root

ARG RDKIT_RELEASE=2022_09_1
ARG BUILD_CONCURRENCY=6

RUN yum update -y
RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-11 bzip2 ca-certificates openssl openssl-devel java-1.8.0-openjdk-devel

RUN rpmkeys --import http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN curl https://download.mono-project.com/repo/centos7-stable.repo | tee /etc/yum.repos.d/mono-centos7-stable.repo
RUN yum install -y mono-devel

RUN groupadd -g 500 docker && \
    useradd -u 500 -s /bin/bash -g docker docker && \
    mkdir /src /work /image /deps && \
    chown -R docker:docker /src /work /image /deps
RUN mkdir -p /home/docker && chown docker:docker /home/docker
USER docker
RUN mkdir -p /work/boost /work/cmake /work/eigen /work/zlib /work/bzip2 /work/freetype /work/swig /work/cairo

WORKDIR /work/zlib
RUN curl -L -O https://zlib.net/zlib-1.2.13.tar.gz
RUN tar xzf zlib-1.2.13.tar.gz
WORKDIR /work/zlib/zlib-1.2.13
RUN source /opt/rh/devtoolset-11/enable && CC="gcc -fPIC" ./configure --static --64 --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

WORKDIR /work/bzip2
RUN curl -L -O https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
RUN tar xzf bzip2-1.0.8.tar.gz
WORKDIR /work/bzip2/bzip2-1.0.8
RUN source /opt/rh/devtoolset-11/enable && make CC="gcc -fPIC" PREFIX=/deps -j${BUILD_CONCURRENCY}
RUN source /opt/rh/devtoolset-11/enable && make CC="gcc -fPIC" PREFIX=/deps -j${BUILD_CONCURRENCY} install

WORKDIR /work/boost
RUN curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2
RUN tar xjf boost_1_80_0.tar.bz2
WORKDIR /work/boost/boost_1_80_0
RUN source /opt/rh/devtoolset-11/enable && ./bootstrap.sh --with-libraries=serialization,iostreams,regex,system --without-icu --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && \
    ./b2 cflags=-fPIC cxxflags=-fPIC --prefix=/work/boost/install variant=release link=static \
        --with-serialization --with-iostreams --with-regex --with-system \
        -sBZIP2_INCLUDE=/deps/include -sBZIP2_LIBPATH=/deps/lib -sZLIB_INCLUDE=/deps/include -sZLIB_LIBPATH=/deps/lib

WORKDIR /work/cmake
RUN curl -L -O https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2.tar.gz
RUN tar xzf cmake-3.24.2.tar.gz
WORKDIR /work/cmake/cmake-3.24.2
RUN source /opt/rh/devtoolset-11/enable && ./bootstrap --prefix=/deps --parallel=16
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

WORKDIR /work/eigen
RUN curl -L -o eigen-3.4.0.tar.bz2 https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.bz2
RUN tar xjf eigen-3.4.0.tar.bz2
WORKDIR /work/eigen/eigen-3.4.0
RUN mkdir build
WORKDIR /work/eigen/eigen-3.4.0/build
RUN source /opt/rh/devtoolset-11/enable && /deps/bin/cmake -DCMAKE_INSTALL_PREFIX=/deps ..
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} install

RUN mkdir -p /work/freetype
WORKDIR /work/freetype
RUN curl -L -O https://download.savannah.gnu.org/releases/freetype/freetype-2.12.1.tar.gz
RUN tar xzf freetype-2.12.1.tar.gz
WORKDIR /work/freetype/freetype-2.12.1
RUN source /opt/rh/devtoolset-11/enable && CC="gcc -fPIC" CXX="g++ -fPIC" ./configure \
     --with-zlib=yes ZLIB_CFLAGS="-I/deps/include" ZLIB_LIBS="-L/deps/lib -lz" \
    --enable-static=yes --enable-shared=no --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

RUN mkdir -p /work/swig
WORKDIR /work/swig
RUN rm -f swig-3.0.12.tar.gz
# Occasionally files downloaded from SourceForge are corrupted, so we try up to 5 times
RUN for i in `seq 1 5`; do \
        curl -L -o swig-3.0.12.tar.gz https://sourceforge.net/projects/swig/files/swig/swig-3.0.12/swig-3.0.12.tar.gz/download && \
        [ `md5sum swig-3.0.12.tar.gz | awk '{print($1 == "82133dfa7bba75ff9ad98a7046be687c")}'` != 0 ] && touch swig_md5_ok && break; \
    done
RUN test -e swig_md5_ok || ( >&2 echo "Failed to download SWIG" && exit 1 )
RUN tar xzf swig-3.0.12.tar.gz
WORKDIR /work/swig/swig-3.0.12
RUN source /opt/rh/devtoolset-11/enable && ./configure --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

WORKDIR /work/cairo
RUN for i in `seq 1 5`; do \
        curl -L -O https://download.sourceforge.net/libpng/libpng-1.6.38.tar.gz && \
        [ `md5sum libpng-1.6.38.tar.gz | awk '{print($1 == "151d579116e601e393e780b7f46b2ff0")}'` != 0 ] && touch libpng_md5_ok && break; \
    done
RUN test -e libpng_md5_ok || ( >&2 echo "Failed to download libpng" && exit 1 )
RUN tar xzf libpng-1.6.38.tar.gz
WORKDIR /work/cairo/libpng-1.6.38
RUN source /opt/rh/devtoolset-11/enable && CC="gcc -fPIC -I/deps/include" \
    LDFLAGS="-L/deps/lib" ./configure \
    --enable-shared=no --enable-static=yes --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

WORKDIR /work/cairo
RUN curl -L -O https://www.cairographics.org/releases/pixman-0.42.0.tar.gz
RUN tar xzf pixman-0.42.0.tar.gz
WORKDIR /work/cairo/pixman-0.42.0
RUN source /opt/rh/devtoolset-11/enable && CC="gcc -fPIC -I/deps/include" \
    LDFLAGS="-L/deps/lib" ./configure \
    --enable-shared=no --enable-static=yes --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

WORKDIR /work/cairo
RUN curl -L -O https://www.cairographics.org/releases/cairo-1.16.0.tar.xz
RUN tar xJf cairo-1.16.0.tar.xz
WORKDIR /work/cairo/cairo-1.16.0
RUN source /opt/rh/devtoolset-11/enable && CC="gcc -fPIC -I/deps/include" \
    PKG_CONFIG_PATH=/deps/lib/pkgconfig \
    ./configure --enable-shared=no --enable-static=yes --prefix=/deps
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install

WORKDIR /src
RUN curl -L -O https://github.com/rdkit/rdkit/archive/refs/tags/Release_${RDKIT_RELEASE}.tar.gz
RUN tar xzf Release_${RDKIT_RELEASE}.tar.gz
WORKDIR /src/rdkit-Release_${RDKIT_RELEASE}
RUN sed -i 's|#if _MSC_VER|#ifdef _WIN32|' Code/GraphMol/catch_chirality.cpp
RUN sed -i 's|Windows\.h|windows.h|' Code/GraphMol/MMPA/MMPA_UnitTest.cpp
RUN sed -i -e 's|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Cairo::Cairo\)|\1target_include_directories(MolDraw2D PUBLIC /deps/include/cairo)\n\1\2 /deps/lib/libcairo.a /deps/lib/libpixman-1.a /deps/lib/libpng16.a|' \
    -e 's|\( *\)\(target_link_libraries(MolDraw2D PUBLIC \)\(Freetype::Freetype\)|\1target_include_directories(MolDraw2D PUBLIC /deps/include/freetype2)\n\1\2 /deps/lib/libfreetype.a /deps/lib/libz.a|' \
    Code/GraphMol/MolDraw2D/CMakeLists.txt
RUN sed -i -e 's|if(WIN32)|if(FALSE)|' \
    -e 's|\(SWIG_LINK_LIBRARIES *( *\)\(GraphMolWrap *\)\(\${RDKit_Wrapper_Libs}\)|\1\2\3 /deps/lib/libpixman-1.a /deps/lib/libpng16.a|' \
    Code/JavaWrappers/gmwrapper/CMakeLists.txt
RUN sed -i 's|\(SWIG_LINK_LIBRARIES *( *\)\(RDKFuncs *\)\(\${RDKit_Wrapper_Libs}\)|\1\2\3 /deps/lib/libpixman-1.a /deps/lib/libpng16.a|' \
    Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
# Patch for Avalon 2.0.3
RUN sed -i -e 's|set(AVALON_VERSION "2\.0\.2")|set(AVALON_VERSION "2.0.3")|' \
    -e 's|set(AVALONTOOLS_MD5SUM "fc188383a8896802e948c977b73dbe71")|set(AVALONTOOLS_MD5SUM "89e083c3c021baec77a2b85a641c86dd")|' \
    External/AvalonTools/CMakeLists.txt
RUN mkdir build
WORKDIR /src/rdkit-Release_${RDKIT_RELEASE}/build
RUN source /opt/rh/devtoolset-11/enable && /deps/bin/cmake \
    -D RDK_BUILD_INCHI_SUPPORT=ON \
    -D RDK_BUILD_AVALON_SUPPORT=ON \
    -D RDK_BUILD_PYTHON_WRAPPERS=OFF \
    -D RDK_BUILD_FREESASA_SUPPORT=ON \
    -D RDK_BUILD_MOLINTERCHANGE_SUPPORT=ON \
    -D RDK_BUILD_COORDGEN_SUPPORT=ON \
    -D RDK_BUILD_CAIRO_SUPPORT=ON \
    -D RDK_INSTALL_INTREE=OFF \
    -D RDK_BUILD_SWIG_WRAPPERS=ON \
    -D RDK_BUILD_SWIG_JAVA_WRAPPER=ON \
    -D RDK_BUILD_SWIG_CSHARP_WRAPPER=ON \
    -D RDK_BUILD_THREADSAFE_SSS=ON \
    -D RDK_USE_BOOST_SERIALIZATION=ON \
    -D RDK_BUILD_CPP_TESTS=ON \
    -D RDK_BUILD_PGSQL=OFF \
    -D Boost_INCLUDE_DIR=/work/boost/boost_1_80_0 \
    -D Boost_LIBRARY_DIR=/work/boost/boost_1_80_0/stage/lib \
    -D Boost_NO_SYSTEM_PATHS=ON \
    -D Boost_NO_BOOST_CMAKE=ON \
    -D CMAKE_BUILD_TYPE=Release \
    -D EIGEN3_INCLUDE_DIR=/deps/include/eigen3 \
    -D ZLIB_LIBRARY=/deps/lib/libz.a \
    -D ZLIB_INCLUDE_DIR=/deps/include \
    -D SWIG_EXECUTABLE=/deps/bin/swig \
    -D SWIG_DIR=/deps/share/swig/3.0.12 \
    -D FREETYPE_LIBRARY=/deps/lib/libfreetype.a \
    -D FREETYPE_INCLUDE_DIRS=/deps/include/freetype2 \
    -D CAIRO_INCLUDE_DIR=/deps/include/cairo \
    -D CAIRO_LIBRARY_DIR=/deps/lib \
    -D CMAKE_INSTALL_PREFIX=/image \
    -DBoost_USE_STATIC_LIBS=ON \
    ..
RUN source /opt/rh/devtoolset-11/enable && make -j${BUILD_CONCURRENCY} && make -j${BUILD_CONCURRENCY} install
