# packages in environment at /Users/build/a3/envs/rdkit_knime:
#
# Name                    Version                   Build  Channel
ansible                   6.6.0                    pypi_0    pypi
ansible-core              2.13.6                   pypi_0    pypi
autoconf                  2.69            pl5340h1230e6a_1  
automake                  1.16.5          pl5340hca03da5_0  
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2022.10.11           hca03da5_0  
certifi                   2022.9.24       py310hca03da5_0  
cffi                      1.15.1                   pypi_0    pypi
cryptography              38.0.3                   pypi_0    pypi
gdbm                      1.18                 h8fe7016_4  
jinja2                    3.1.2                    pypi_0    pypi
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.2                hc377ac9_4  
m4                        1.4.18               h1230e6a_1  
markupsafe                2.1.1                    pypi_0    pypi
ncurses                   6.3                  h1a28f6b_3  
openssl                   1.1.1s               h1a28f6b_0  
packaging                 21.3                     pypi_0    pypi
perl                      5.34.0               h1a28f6b_2  
pip                       22.2.2          py310hca03da5_0  
pycparser                 2.21                     pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.10.6               hbdb9e5c_1  
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
resolvelib                0.8.1                    pypi_0    pypi
setuptools                65.5.0          py310hca03da5_0  
sqlite                    3.39.3               h1058600_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2022f                h04d1e81_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.6                h1a28f6b_0  
zlib                      1.2.13               h5a0b063_0  
